// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PPM;

#nullable disable

namespace webapi.Migrations
{
    [DbContext(typeof(PPMDBContext))]
    [Migration("20250610041504_UpdatedDataModels")]
    partial class UpdatedDataModels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("webapi.Models.Event", b =>
                {
                    b.Property<int>("event_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("event_id"));

                    b.Property<string>("event_description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("event_end_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("event_end_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("event_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("event_start_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("event_start_time")
                        .HasColumnType("datetime2");

                    b.HasKey("event_id");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("webapi.Models.Park", b =>
                {
                    b.Property<int>("park_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("park_id"));

                    b.Property<int>("acres")
                        .HasColumnType("int");

                    b.Property<int>("baseball_fields")
                        .HasColumnType("int");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("disc_golf_courses")
                        .HasColumnType("int");

                    b.Property<int>("fishing_spots")
                        .HasColumnType("int");

                    b.Property<string>("geolocation")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("number_of_pavillions")
                        .HasColumnType("int");

                    b.Property<string>("park_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("play_structures")
                        .HasColumnType("int");

                    b.Property<int>("soccer_fields")
                        .HasColumnType("int");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("street_address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("trails")
                        .HasColumnType("int");

                    b.Property<int>("volleyball_courts")
                        .HasColumnType("int");

                    b.Property<string>("zipcode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("park_id");

                    b.ToTable("Parks");
                });

            modelBuilder.Entity("webapi.Models.Registration", b =>
                {
                    b.Property<int>("registration_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("registration_id"));

                    b.Property<DateTime>("end_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("event_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_approved")
                        .HasColumnType("bit");

                    b.Property<int>("park_id")
                        .HasColumnType("int");

                    b.Property<int>("pavillion")
                        .HasColumnType("int");

                    b.Property<string>("requested_park")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("start_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.Property<int>("waitlist")
                        .HasColumnType("int");

                    b.HasKey("registration_id");

                    b.ToTable("Registration");
                });

            modelBuilder.Entity("webapi.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("first_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("is_admin")
                        .HasColumnType("bit");

                    b.Property<string>("last_name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
